# Generated by Django 3.2.5 on 2022-06-28 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='username',
            new_name='nickname',
        ),
    ]
